####
# Codon Count ####
####


#' getCodonCount
#'
#' get singleton or pair codon count table for a set of sequences
#'
#' @param strings a set of sequences to count codons
#' @param mode codon counting mode: singleton or pair
#' @param string_chunks the number of chunks to divide sequence list, default: 20
#'
#' @import Biostrings
#'
#' @export
#'
getCodonCount <- function(strings, mode = "singleton", string_chunks = 20){

  # functions
  require(Biostrings)

  # get width and step for codon counting mode
  if(mode == "singleton"){
    width <- 3
    code <- GENETIC_CODE
  } else if(mode == "pair") {
    width <- 6
    code <- getPairGENETIC_CODE()
  } else {
    stop("Mode should be either 'singleton' or 'pair'")
  }

  # seperate the sequence list into chunks
  chunk <- function(x,n) split(x, factor(sort(rank(x)%%n)))
  strings_ind_list <- chunk(1:length(strings), 20)
  stringscodon <- NULL

  # get codon count
  for(i in 1:length(strings_ind_list)){
    temp <- oligonucleotideFrequency(strings[strings_ind_list[[i]],], width = width, step = 3)
    temp <- data.frame(temp, row.names = names(strings[strings_ind_list[[i]],]))
    stringscodon <- rbind(stringscodon, temp)
  }

  # sort columns by codon order
  stringscodon <- stringscodon[,names(code)]

  # return
  return(stringscodon)
}

#' aggregateCodonCount
#'
#' aggregate the codon counts for a given set of grouping for the initial set of sequences
#'
#' @param strings_codon the codon count table generated by getCodonCount(strings)
#' @param group an additional table for grouping information of sequences
#'
#' @export
#'
aggregateCodonCount <- function(strings_codon, group_table){

  # check grouping data
  if(!all(colnames(group_table) %in% c("seqID", "Group")))
    stop("Make sure that group table only has two columns 'seqID' and 'group'")

  # common sequences
  commonIDs <- intersect(rownames(strings_codon), group_table$seqID)
  if(length(commonIDs) == 0)
    stop("No sequence ID matches with the grouped sequences")

  # join tables
  strings_codon <- data.frame(seqID = rownames(strings_codon), strings_codon) %>% left_join(group_table)

  # aggregate table
  strings_codon_group <- aggregate(strings_codon[,!colnames(strings_codon) %in% c("seqID", "Group")],
                                   list(strings_codon$Group), sum)
  strings_codon_group <- data.frame(strings_codon_group[,!colnames(strings_codon_group) %in% "Group.1"], row.names = strings_codon_group$Group.1)

  # return
  return(strings_codon_group)
}

#' getPairGENETIC_CODE
#'
#' get pairs of AA from Biostrings::GENETIC_CODE
#'
#' @export
#'
getPairGENETIC_CODE <- function(){

  # library
  require(Biostrings)

  # get pairs
  GENETIC_CODE_PAIR <- as.vector(outer(GENETIC_CODE, GENETIC_CODE, FUN=paste0))

  # get names for pairs
  names(GENETIC_CODE_PAIR) <-  as.vector(outer(names(GENETIC_CODE), names(GENETIC_CODE), FUN=paste0))

  # return
  return(GENETIC_CODE_PAIR)
}

